version: '3.8'

services:
  flask:
    container_name: flask-oct-app
    image: syedahmedarees/21-oct-flask-app-2:v10
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    build: ./nginx
    ports:
      - "8081:80"
    depends_on:
      - flask

volumes:
  db_data:

